/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/teams/{domain}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** メモを検索する */
        get: {
            parameters: {
                query: {
                    /** @description 検索クエリ */
                    q: string;
                    /** @description ページ番号 */
                    page?: number;
                    /** @description 1ページあたりのアイテム数 */
                    per_page?: number;
                };
                header?: never;
                path: {
                    /** @description チームドメイン */
                    domain: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description メモ */
                            posts?: components["schemas"]["Post"][];
                            /** @description メタデータ */
                            meta?: {
                                /** @description 前のページのURL */
                                previous_page?: string | null;
                                /** @description 次のページのURL */
                                next_page?: string | null;
                                /** @description 合計数 */
                                total?: number;
                            };
                        };
                    };
                };
                /** @description 不正なリクエスト */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 認証エラー */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description リクエスト回数制限 */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{domain}/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** メモの詳細を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description チームドメイン */
                    domain: string;
                    /** @description メモID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Post"];
                    };
                };
                /** @description 認証エラー */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description メモが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Post: {
            /** @description ID */
            id?: number;
            /** @description タイトル */
            title?: string;
            /** @description 本文 */
            body?: string;
            /** @description 下書きかどうか */
            draft?: boolean;
            /** @description アーカイブされているかどうか */
            archived?: boolean;
            /** @description URL */
            url?: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updated_at?: string;
            /** @description 公開範囲 */
            scope?: string;
            /** @description 共有URL */
            sharing_url?: string | null;
            /** @description タグ */
            tags?: {
                /** @description タグ名 */
                name?: string;
            }[];
            /** @description ユーザー情報 */
            user?: {
                /** @description ユーザーID */
                id?: number;
                /** @description ユーザー名 */
                name?: string;
                /** @description プロフィール画像URL */
                profile_image_url?: string;
            };
            /** @description スター数 */
            stars_count?: number;
            /** @description Good Job数 */
            good_jobs_count?: number;
            /** @description コメント */
            comments?: Record<string, never>[];
            /** @description グループ */
            groups?: {
                /** @description グループID */
                id?: number;
                /** @description グループ名 */
                name?: string;
            }[];
            /** @description 代表画像URL */
            representative_image_url?: string | null;
            /** @description 添付ファイル */
            attachments?: Record<string, never>[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
